baseURL = "https://christopherbarrington.github.io/ainsley"
languageCode = "en-gb"
title = "The Marlington Recipe Book"
# theme = "recipe-book"

[params]
  author = "Christopher Barrington"
  description = "Recipes collected by The Marlingtons"
  github = "ChristopherBarrington/ainsley"

[outputs]
  home = ["HTML","RSS", "JSON", "SearchIndex"]
  section = ["HTML","RSS", "JSON"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "searchindex"
    isPlainText = true
